package ingsw.utilities;

public enum ToolCardType {
    COPPER_FOIL_BURNISHER,
    CORK_BACKED_STRAIGHT_EDGE,
    EGLOMISE_BRUSH,
    FLUX_BRUSH,
    FLUX_REMOVER,
    GLAZING_HAMMER,
    GRINDING_STONE,
    GROZING_PLIERS,
    LATHEKIN,
    RUNNING_PLIERS,
    TAP_WHEEL,
    LENS_CUTTER,
    DRAFT_POOL,
    PATTERN_CARD,
    ROUND_TRACK,
    AVOID_USE
}
