package ingsw.utilities;

public enum ToolCardType {
    COPPER_FOIL_BURNISHER,
    CORK_BARCKED_STRAIGHT_EDGE,
    EGLOMISE_BRUSH,
    FLUX_BRUSH,
    FLUX_REMOVER,
    GLAZING_HAMMER,
    GRINDING_STONE,
    GROZING_PLIERS,
    LATHEKIN,
    RUNNING_PLIERS,
    TAP_WHEEL,
    DRAFT_POOL,
    PATTERN_CARD,
    ROUND_TRACK
}
